### ISSUE TITLE
Property confidence should work differently

### ISSUE THREAD

**Issue by Toilal** [wackou/guessit#159]
I think guessit would be better if we change the way confidence works.

Today, for a property called `prop` for example, if we found a value `A` with a confidence of `0.8` and a value `B` with a confidence of `0.6`, then nothing will be returned. 

That's because on final step, flexget will keep only `A`, the highest confidence property, and change it's confidence using a difference `0.8 - 0.6` = `0.2`. Then `prop` is dropped because `0.2` is too low.

What would have been better is returning `A` with it's original confidence, and `B` in dict dedicated to dropped values, like this ...

    {'prop': 'A', 'collision': {'prop': 'B'}}

Then, the application can solve the collision data to check which value is the right one (`A` or `B`) using manual intervention, database lookup or predefined rules (out of guessit scope) ...

It would help to solve #142, by giving the absolute episodes in the main dict, and the relative ones in the collision dict.

**Comment by Toilal** [comment]
Actually, confidence is used when multiple values are found for the same property (ie. multiple `episodeNumber`, or multiple `year`). But confidence value is defined at the pattern level. Most of the time, a same pattern match multiple times, and gives the same confidence for distinct values.

It doesn't really help to find out which is the property to keep. In fact, the only way to estimate the confidence of a property value is probably based on other guessed properties for this case

I think confidence (as it's defined today) could be dropped, and replaced by a standard simple default merging strategy (ie. keep the first one from the filename part of the string).

transformers could define a `merge` function to implement advanced and specific merging strategies.

It will also help to solve #190 because we could implement something that keep the property from the filename, even if another value is defined in the directory.

**Comment by Toilal** [comment]
Commit f7c067f161e3a937c972745a62321c73c8fa07bb introduced some change to the computation of confidence. When merging properties `p1` and `p2` with respective confidence `c1` and `c2` (`c1` > `c2`), instead of computing `(c1 - c2)`, we are now computing `(c1 * 2 - c2 * 2 / 2)`.

 It allows to set a higher confidence for the property to keep than before, and avoid to compute a 0 confidence when two properties have the same confidence. When two properties have the same confidence, the first one is keeped with half it's confidence, and the second one is dropped.

I still think confidence is quite hard to maintain, but currently it just work well and it was usefull to fix #190, so I close this one too.

**Comment by wackou** [comment]
you know that (c1 - c2) and (c1*2 - c2*2) / 2 are absolutely equal, right? It's a bit weird that it fixed it...

**Comment by Toilal** [comment]
Guru Meditation ! :) Sorry you are right, I don't really know what it've done, i'll have a look during the day :)

**Comment by Toilal** [comment]
This change probably has nothing to do with #190 bugfix.

**Comment by Toilal** [comment]
I think I wanted to do `c1 - (c2 / 2)` ...
