### ISSUE TITLE
Enhancement Request: Additional media detection types

### ISSUE THREAD

**Issue by magixx** [wackou/guessit#180]
Any plans to detection for all other release types? e.g. games, software, mp3, audiobooks...
I'm currently looking into doing this and am trying to see if it would be easier to start from scratch or look into how such a project already works and add to it. My goals is so that given a release name I could figure out what category it likely belongs to and most information about it such as title, resolutions, source...
A couple of resources that I'm using so far to essentially just collect tags and information are http://scenerules.irc.gs/, Sickbeard, autodl-irssi-community, headphones, sonarr, sick-beard, and some predb databases to try and find common tags.
Any tips or suggestions?

**Comment by Toilal** [comment]
It would be really easier to implement this using guessit 2 and rebulk, but it's still to much work for me. 

I'm closing this for now, but feel free to contribute ...
