### ISSUE TITLE
DeprecationWarning with latest setuptools

### ISSUE THREAD

**Issue by gazpachoking** [wackou/guessit#183]
Looks like the 10.2 setuptools updated deprecated a method being used by guessit, causing this warning to be issued:

```DeprecationWarning: `require` parameter is deprecated. Use EntryPoint._load instead.```

The code causing the warning is:

https://github.com/wackou/guessit/blob/0.10.0/guessit/plugins/transformers.py#L90

**Comment by Toilal** [comment]
Thx @gazpachoking I'll publish a bugfix release.

**Comment by Toilal** [comment]
Changes did not fixed the warning message on some versions ...
