### ISSUE TITLE
UserWarning: Module readline was already imported

### ISSUE THREAD

**Issue by grplyler** [wackou/guessit#186]
After upgrading from an older version of guessit to 0.10.0 I get an annoying print out when I importing the guessit module:

    Python 2.7.7 (v2.7.7:f89216059edf, May 31 2014, 12:53:48)
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import guessit
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/guessit-0.10.2.dev0- 
    py2.7.egg/guessit/__init__.py:23: UserWarning: Module readline was already imported from     
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so, but 
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages is being added to 
    sys.path
    import pkg_resources
    >>>

Any advice on this matter is much appreciated. I love guessit!

**Comment by Toilal** [comment]
It should be fixed with https://github.com/wackou/guessit/commit/b899db3e94ec0d6367fa889aa45bf228a77009b7

It's included in `0.10.1`, can you confirm it doesn't warn using this version ?
