### ISSUE TITLE
Incorrectly classify archlinux as serie

### ISSUE THREAD

**Issue by kamaradclimber** [wackou/guessit#187]
`guessit "/home/noemi/torrent/archlinux-2015.03.01-dual.iso"`

returns:
```
GuessIt found: {
    [1.00] "type": "episode",
    [1.00] "container": "iso",
    [1.00] "mimetype": "application/x-iso9660-image",
    [1.00] "date": "2015-03-01",
    [0.60] "series": "archlinux"
}
```

Archlinux is a linux distribution :)

btw, `guessit --bug`  seems currently broken (but is a really good idea to help bug reporting)

**Comment by kamaradclimber** [comment]
You can close this issue if you think it is not guessit responsability to identify this as "unknown type".

**Comment by Toilal** [comment]
100% true, we can't guess filetypes from all the filesystem :)
