### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by kamaradclimber** [wackou/guessit#189]
It seems that guessit deals incorrectly with encoding:

`guessit torrent/les\ sept\ samouraïs/les\ sept\ samouraïs.avi` returns: 

```
For: torrent/les sept samouraïs/les sept samouraïs.avi
GuessIt found: {
    [1.00] "type": "movie",
    [1.00] "container": "avi",
    [0.80] "title": "les sept samoura\u00efs",
    [1.00] "mimetype": "video/x-msvideo"
}
```

Environment might help:
```
SHELL=/bin/bash
TERM=xterm
LC_COLLATE=C
LANG=en_US.UTF-8
```

running python 3.4.2 on archlinux.

Same error happens for é et è characters.

**Comment by Toilal** [comment]
The problem only occurs on display. If you use guessit from API, strings are properly defined.

guessit output is encoded to avoid crash when displaying UTF-8 characters on non UTF-8 console.

**Comment by kamaradclimber** [comment]
Is there a way to make it display utf8 characters on utf8 consoles ?
I use guessit from a bash script to classify some of downloaded files.

**Comment by Toilal** [comment]
@kamaradclimber It was just something weird when calling `json.dumps`. It's fixed now in master.

**Comment by kamaradclimber** [comment]
thanks a lot
