### ISSUE TITLE
Adopt pytest as a runner and framework

### ISSUE THREAD

**Issue by nicoddemus** [wackou/guessit#191]
Hi,

In April the [pytest](pytest.org) team is holding "adopt pytest month" to encourage projects to consider using pytest, by pairing open source projects with experienced pytest helpers (myself included). I've used guessit in [ss](https://github.com/nicoddemus/ss) and find it a great project. I noticed you have a vast test suite written in xUnit, so you would be a prime candidate for participating. Note that pytest can run xUnit tests like those in your test suite without modifications, so the migration can be made in any pace you like, but you would have immediate access to pytest awesome features like distributed testing, dozens of plugins and more.

Check out http://pytest.org/latest/adopt.html if you are interested. :smile:

Cheers! :beer:

**Comment by Diaoul** [comment]
I've looked into pytest for my own library subliminal but I couldn't find the added value so I'm really curious about how this will turn out.
Had a look into ss, looks like it shares the same goal as subliminal :+1:

**Comment by nicoddemus** [comment]
I take it you're interested then? Great! :smile:

> Had a look into ss, looks like it shares the same goal as subliminal

Yep! Unfortunately I found subliminal only after I have already written ss (in fact, it was through subliminal that I found guessit and incorporated it into ss). But I added other small features I wanted too (like `mkv` file generation), so it is a nice pet project for me. :smile:

Please let this issue open because we plan to contact you through here when we start working next month.

Cheers! :beers:

**Comment by wackou** [comment]
I'm all for using pytest, have used it myself a bit and I really like the error reporting more than xUnit style. However, as you said, pytest is able to run guessit tests already, so I'm not sure what we would gain from tighter integration with pytest, especially when this means that we would remove the possibility for the python unittest module to run the tests.

As for reducing boilerplate in the tests, most of them are already read from yaml files, so there is as little boilerplate as possible.

Would be interested in hearing your thoughts on what clear benefits we would gain from using pytest as our only test runner, though, as I really like the project.

**Comment by nicoddemus** [comment]
> Would be interested in hearing your thoughts on what clear benefits we would gain from using pytest as our only test runner, though, as I really like the project.

@wackou I'm not really sure, I saw your test suite and I understand your points, but I guess only after working with it a little we will be able to answer that for sure; it depends on the project, but pytest has several features like plain asserts, `parametrize`, marks and fixtures which really shine once you see them applied. Plain asserts to me is already a good enough reason (once you get to writing just plain asserts in your code, you never want to go back to write `self.assertEqual` again :wink:), but of course your mileage may vary.

> ... especially when this means that we would remove the possibility for the python unittest module to run the tests.

Personally I don't see removing the possibility of running the tests using python's unittest module as a problem, pytest is a small dependency and used only for development. Can you share your concerns regarding that?

Also, please keep in mind that adopting it at the end of the exercise is entirely up to the team, you might decide to not do it after all if you don't see much gains for the project. :grin: 

Cheers! :beers:

**Comment by wackou** [comment]
> once you get to writing just plain asserts in your code, you never want to go back to write self.assertEqual again :wink:

oh, I agree here, but I'm not sure it's reason enough for a complete switch.

As to why keep the ``unittest`` compatibility, here are 2 reasons:
- people seem to want it: see https://github.com/wackou/guessit/issues/30
- they are running like that on travis (they surely have pytest compatibility, but still)

I agree that those might be weak arguments, as pytest can probably handle all of this, but it's already working, so why change it if there's no clear benefit?...

If you come up with a clean pull request that implements it, I would still probably merge it though, as I really like the project, but TBH I don't really have the time myself to work on this... If you're still motivated, then please keep this thread alive :wink:

**Comment by nicoddemus** [comment]
> so why change it if there's no clear benefit?

I agree with that sentiment, and we might just as well arrive at that conclusion. :grin:

> If you come up with a clean pull request that implements it...

That's the idea, some progressive PRs converting some tests and showing off features, in incremental steps. This way it's easier to follow what's going on and discuss any unclear points.

> If you're still motivated, then please keep this thread alive

Great, glad you guys are open to this.

Cheers! :beers:

**Comment by bsravanin** [comment]
Hi,

I am the volunteer to help with guessit adopting pytest. As already discussed in the conversation above, guessit tests can already be run with pytest without any code changes. I changed the tox.ini to also use it.

I also tried to run it with pytest-xdist (parallelized tests), and didn't see much of a benefit yet. It is a trivial change, so we can always add them in the future if the number of tests or their time taken increases.

Do you in particular have any specific pytest features that you want guessit tests to be able to benefit from?

Regarding code changes, which I will make:
1. Are you okay with switching from the self.assert* to plain asserts?
2. What about removing any boilerplate code related to adding tests to suites or enabling test runner in each test file? (I think it is really useful to remove them and not have to keep maintaining them in the future.)

**Comment by Toilal** [comment]
Seems good for me, feel free to open a pull request.

**Comment by wackou** [comment]
ok for me too. Let's discuss the details on the pull request :)

**Comment by wackou** [comment]
one question: will I have to make some changes on travis-ci or will the tests automatically work there?

**Comment by bsravanin** [comment]
I have never used travis-ci. Does it simply run the tox command to run tests? If so, you will not need to make any changes to that.

I have made the changes I planned to: the latest 4 commits in https://github.com/bsravanin/guessit/commits/master. I have a question before I submit a pull request.

When I enabled doctests, I started getting import errors about fabric.api and pygments.style. I am not familiar with either. Do these need to be added to dev-requirements? Is fabfile related to these?

**Comment by wackou** [comment]
yes, I guess travis uses the tox.ini file to run the tests, so I imagine there shouldn't be a problem there.

fabric is an automation tool, I use it to define some commonly used tasks. The fabfile (https://github.com/wackou/guessit/blob/master/fabfile.py) is the "configuration" file for it, if you want. The problem with it (I imagine) is that it's still not compatible with python3! You can ignore it for now, I should probably replace it with something more adapted (such as doit: http://pydoit.org/) or drop it altogether, it's not used that much in guessit anymore anyway... 

As for pygments, this is the python module used to colorize source code. I don't know why it fails for you, but it's not required for guessit at all. Maybe for building the docs, but guessit itself doesn't use it.

**Comment by bsravanin** [comment]
Ok, thank you. I will give it another try. Should be able to get doctests running with pytest as part of the tox run.

**Comment by Toilal** [comment]
travis doesn't use `tox.ini`, but `travis.yml`. tox is a handy way to execute test in a development environment, but travis doesn't run it as it has its own environment matrix with distributed test environment (in VMs).

**Comment by nicoddemus** [comment]
Hi,

Just thought I would mention that is possible to use `tox` in traves, here's [an example](https://github.com/pytest-dev/pytest-faulthandler/blob/master/.travis.yml).

Cheers,

**Comment by Toilal** [comment]
Yes, but it's better to use the travisCI matrix for the build to be
distributed on distinct VMs for each python version.

**Comment by nicoddemus** [comment]
Actually Travis has a single VM for Python, the `python` configuration in `travis.yaml` is mostly used to create your starting virtual environment and  `tox` works fine because creates its own virtual environment using the python interpreters found in the system to run the tests.

Here's another example: [pytest-faker](https://github.com/pytest-dev/pytest-faker/blob/master/.travis.yml). If you look at the output of [some of its builds](https://travis-ci.org/pytest-dev/pytest-faker), you can see from the tox output it is in fact testing against different python versions.

Please note that I just wanted to point out that `tox` does work on Travis, but of course it's a matter of preference to use it in Travis or not. :smile:

**Comment by Toilal** [comment]
Yes pytest-faker configuration is better, as it creates one travisCI job per Python version.

I would prefer using raw travisCI python matrix though. Tox is a great tool, but i'm not sure it adds value to travisCI build system.

Also, guessit is packaged in some linux distros (archlinux, debian). I would be agree to include pytest as the default test runner and framework, but it should not change the build process for package managers. So running  `python setup.py test` should execute tests, and `python setup.py build` should build the library. Maybe it's possible with a change to setup.py ?

**Comment by nicoddemus** [comment]
> So running  python setup.py test should execute tests, and python setup.py build should build the library. Maybe it's possible with a change to setup.py ?

Sure, there's an example [here](http://pytest.org/latest/goodpractises.html?highlight=setup#integrating-with-distutils-python-setup-py-test).

Cheers,

**Comment by Toilal** [comment]
So with this change, there's nothing to change in travis nor tox, because they both invoke the distutils test command.

@bsravanin If you are still OK to make a PR, it would be great. Use the example provided by @nicoddemus to support distutils / setup.py properly, and keep travis.yml / tox.ini untouched.

**Comment by bsravanin** [comment]
Will do, thank you.

**Comment by wackou** [comment]
@bsravanin by the way, I replaced the fabfile.py which imports fabric with a doit file, so you shouldn't get the import problem with fabric anymore.

**Comment by bsravanin** [comment]
Thank you @wackou. That fixed the fabfile errors, though dodo.py needs a trivial change to use print from future (because of file=sys.stderr). I changed that as part of my pull request https://github.com/wackou/guessit/pull/198, that includes the pytest changes we've discussed so far in this thread. (No changes to tox.ini. Instead using TestCommand in setup.py.)

Doctests still have three problems. No more pygments issues because I added that to test requirements.

1. One doctest in guessit.guess.choose_string fails for Python 2.6.9:
```
314     >>> s(choose_string(('Hello', 0.4), ('Hello World', 0.4)))
Expected:
    ('Hello', 0.64)
Got:
    ('Hello', 0.64000000000000001)
```

2. Discovering doctests as part of the tox run seems very slow (an additional 15s) which doesn't happen when running them directly inside an activiated tox virtualenv.

3. The ```--doctest-modules``` option of pytest used to discover them is throwing an error about that option being unrecognized, despite actually discovering and running those tests without errors. I will have to ask someone in pytest about those.

**Comment by Diaoul** [comment]
I'm currently working with pytest for my own projects including subliminal. What's the best practice for loading test data with pytest? A fixture that returns the data (as list or dict)?

**Comment by bsravanin** [comment]
@Diaoul, it depends on the use cases. If the test data is small enough and localized enough, you could get away with loading the data from yaml files there. If that data has the potential for reuse, moving that to a fixture with a scope of module/session will be faster. You mentioned a list or dict, so in case the test data is to run the same test with multiple inputs, also checkout https://pytest.org/latest/example/parametrize.html if you haven't used it before.

**Comment by Diaoul** [comment]
Would that make sense to use parametrize for guessit on the loaded data from yaml files?

**Comment by bsravanin** [comment]
I see there are a couple of places where yamls are being loaded. I will take a look this week and see if it can benefit from any changes. Thank you for raising the question.

**Comment by bsravanin** [comment]
I didn't get a chance to look at the fixtures stuff last week. I will try this week.

**Comment by wackou** [comment]
closing this as pull request https://github.com/wackou/guessit/pull/199 has been merged

**Comment by pfctdayelise** [comment]
Hey @wackou - if you have a chance, would you mind completing a survey about Adopt Pytest Month? http://goo.gl/forms/sc64SmQNRn
Although guessit took part kind of informally, it looks like it was pretty successful :) I would love to hear about any suggestions you have for making it better.
Thanks,
Brianna
