### ISSUE TITLE
Guessed country is not unicode

### ISSUE THREAD

**Issue by gregdel** [wackou/guessit#192]
I'm using Flask to "jsonify" the result from guessit. If the country is guessed, the jsonify function is not working and the server returns a 500 error.

I've had the same issue with the guessit API on guessit.io for this filename.

Example:
print guess_file_info('Scandal.US.S04E01.HDTV.x264-LOL.mp4')
{u'mimetype': u'video/mp4', u'episodeNumber': 1, u'videoCodec': u'h264', u'container': u'mp4', u'format': u'HDTV', u'series': u'Scandal (US)', u'releaseGroup': u'LOL', u'season': 4, 'country': 'US', u'type': u'episode'}

If I delete the "country" key from the dictionary, the jsonify function works fine.

**Comment by Toilal** [comment]
Language and Country guesses are [babelfish](https://github.com/Diaoul/babelfish) objects. 

They have a default string representation (2 letters), but you can also retrieve the fullstring representation on those objects.

Sadly it's not possible to make those objects support default json serialization, but currently you can implement a custom converter to support them.

```python
from json import JSONEncoder
class DefaultEncoder(JSONEncoder):
    def default(self, o):
        return str(o)

print json.dumps(guessit_result, cls=DefaultEncoder)
```

Set StackOverflow related questions :

http://stackoverflow.com/questions/3768895/python-how-to-make-a-class-json-serializable
http://stackoverflow.com/questions/18478287/making-object-json-serializable-with-regular-encoder

You also need to find out how to register a custom JSONEncoder into Flask.
