### ISSUE TITLE
http 500 on "Scandal.US"

### ISSUE THREAD

**Issue by ludoo0d0a** [wackou/guessit#202]
Scandal.US.S04E21.720p.HDTV.x264

http://guessit.io/guess?filename=Scandal.US.S04E21.720p.HDTV.x264 give http 500 !!

but Scandal.S04E21.720p.HDTV.x264 passes...

**Comment by wackou** [comment]
nice catch! I will look into it ASAP...

**Comment by wackou** [comment]
Thanks again for the report, this should be fixed now!

**Comment by wackou** [comment]
btw, if you're gonna call it with the name of the file but without the extension (ie: no .avi, .mkv, etc.), then I recommend you call it using the ```name_only``` option:
```
http://guessit.io/guess?filename=Scandal.US.S04E21.720p.HDTV.x264&name_only=true
```
This will avoid to detect the last part of the filename (```.x264```) as extension.

**Comment by ludoo0d0a** [comment]
Thanks it works :)
