### ISSUE TITLE
Support for .VOB files

### ISSUE THREAD

**Issue by Fleker** [wackou/guessit#205]
VOB is a video format that should be supported. At the very least, it should be parsed in a similar way to other video formats.

For example:
http://guessit.io/guess?filename=Hot.Fuzz[2007]DvDrip[Eng]-aXXo.avi
 
    {"title": "Hot Fuzz", "language": ["en"], "format": "DVD", "year": 2007, "unidentified": ["aXXo"], "type": 
    "movie", "container": "avi", "mimetype": "video/x-msvideo"}

http://guessit.io/guess?filename=Hot.Fuzz[2007]DvDrip[Eng]-aXXo.vob
  
    {"unidentified": ["aXXo", "Hot Fuzz", "DvDrip", "Eng", "2007"], "type": "unknown", "extension": "vob"}

**Comment by miigotu** [comment]
`"unidentified": ["aXXo"]` is also wrong, should be the release group

**Comment by Toilal** [comment]
I'm fixing this, but release group is not strong enough to be catched.
