### ISSUE TITLE
Bad guessing for "12 monkeys" series

### ISSUE THREAD

**Issue by ldotlopez** [wackou/guessit#210]
Information for '12 Monkeys S01E05.mp4' is incorrect, expected series is "12 Monkeys"
<pre>
$ guessit -t episode '12 Monkeys S01E05.mp4'
For: 12 Monkeys S01E05.mp4
GuessIt found: {
    [1.00] "season": 1,
    [1.00] "type": "episode",
    [0.60] "episodeNumber": 5,
    [0.50] "series": "Monkeys",
    [1.00] "mimetype": "video/mp4",
    [1.00] "container": "mp4"
}
</pre>

**Comment by Toilal** [comment]
It's related to #188 but I keep this one open because this case is "easier" to solve than #188.

`S01E05` should have priority over `12`, and so `12` should remain unmatched. 

It's also related to #159.

**Comment by Toilal** [comment]
I've managed to fix this issue for 12 Monkeys, but it break another test case : 

```
03-Criminal.Minds.5x03.Reckoner.ENG.-.sub.FR.HDTV.XviD-STi.[tvu.org.ru].avi
...
FAILED: 'series': expected = 'Criminal Minds' - received = '03-Criminal Minds'
```

Which behavior is the best ? Shoud I drop this test and replace it by the 12 monkeys test ? @wackou any idea ?

**Comment by Toilal** [comment]
I've changed the unit test from `03-Criminal.Minds.5x03.Reckoner.ENG.-.sub.FR.HDTV.XviD-STi.[tvu.org.ru].avi` to `Criminal.Minds.5x03.Reckoner.ENG.-.sub.FR.HDTV.XviD-STi.[tvu.org.ru].avi`. I think it's a far more common case.
