### ISSUE TITLE
Can't submit bugs

### ISSUE THREAD

**Issue by OmgImAlexis** [wackou/guessit#215]
I've had quite a few incorrect matches so I tried using the the ``--bug`` flag and it won't let me.
``Could not submit bug at the moment, please try again later.``

**Comment by Toilal** [comment]
FYI, bug reported throw the webservice is available at http://guessit.io/bugs

**Comment by OmgImAlexis** [comment]
@Toilal is the pip updated or just the repo?

**Comment by Toilal** [comment]
Only the repo, but i'll perform a release soon.

**Comment by OmgImAlexis** [comment]
Okay, good. I've got about 10 different files all with issues.

**Comment by Toilal** [comment]
@OmgImAlexis please open an issue manually here for those failing files.

**Comment by Toilal** [comment]
@OmgImAlexis I've just released 0.10.4. Available on pypi and in release page of the repo.
