### ISSUE TITLE
guessit API returns 500 on filenames that have 'MULTi' keyword

### ISSUE THREAD

**Issue by aidan-** [wackou/guessit#224]
Hi,

Not sure if this is the appropriate place to put this as it looks to only be affecting the Guessit API and not the library itself.  Certain file names that include the keyword 'MULTi' and a file extension result in a `500 Internal Server Error` response.  Using the library directly with the same filename results in a correct result.

**API**:
```
aidan$ curl "http://guessit.io/guess?filename=some.movie.2015.MULTi.720p.bluray-group.iso"
<html>
  <head>
    <title>500 Internal Server Error</title>
  </head>
  <body>
    <h1>500 Internal Server Error</h1>
  </body>
</html>
```

**library**:
```
aidan$ guessit "some.movie.2015.MULTi.720p.bluray-group.iso"
For: some.movie.2015.MULTi.720p.bluray-group.iso
GuessIt found: {
    [1.00] "mimetype": "application/x-iso9660-image", 
    [1.00] "container": "iso", 
    [0.30] "language": [
        "mul"
    ], 
    [0.60] "title": "some movie", 
    [1.00] "format": "BluRay", 
    [1.00] "releaseGroup": "group", 
    [1.00] "screenSize": "720p", 
    [1.00] "year": 2015, 
    [1.00] "type": "movie"
}
```

Something as simple as this results in the same error:
`curl "http://guessit.io/guess?filename=MULTi.iso"`

**Comment by Toilal** [comment]
@wackou I think it's because Language objects fails to get serialized to JSON in the web API. Could you confirm ?

**Comment by wackou** [comment]
this happened because Language('multi') doesn't have a 2-letter code and that's what the webservice tried to return. It is now fixed (and returns the 3-letter code if the 2-letter code isn't available). Thanks for the report!

**Comment by Diaoul** [comment]
You should use str() to convert a Language to its ietf form.

**Comment by wackou** [comment]
@Diaoul you're right, that's even easier and more idiomatic. What was I thinking? :smile: 

https://github.com/wackou/guessitserver/commit/c757685c0bfcbfb19a2d70be306a17d63e6f7a17
