### ISSUE TITLE
Unable to determine identity with long season number

### ISSUE THREAD

**Issue by dingho** [wackou/guessit#226]
I'm unable to identify files when the season is a year (4 digits). I have to manually specify each episode. For example:
Looney Tunes 1940x01 Porky's Last Stand.mkv

Other shows will automatically be detected no problem, so I'm wondering if it's the long season (4 digits instead of 2). I've tried multiple formats as well, i.e. 1940x01 and S1940E01. Same problem.

**Comment by Toilal** [comment]
in this case, would you prefer to have 1940 identified are `year` or `season` property ?

**Comment by dingho** [comment]
I'd prefer it as the season as this is how tvdb is identifying it.  Thanks.

**Comment by Toilal** [comment]
Using S1940E01, it is identified as both `year` and `season` property. Which version are you using ?

```
For: Looney Tunes S1940E01 Porky's Last Stand.mkv
GuessIt found: {
    [1.00] "type": "episode",
    [1.00] "container": "mkv",
    [1.00] "episodeNumber": 1,
    [1.00] "season": 1940,
    [0.50] "title": "Porky's Last Stand",
    [0.70] "series": "Looney Tunes",
    [1.00] "mimetype": "video/x-matroska",
    [1.00] "year": 1940
}
```

**Comment by Toilal** [comment]
I understand why this issue occurs.

This kind of pattern can collides with custom `screenSize` patterns. ```Pirates de langkasuka.2008.FRENCH.1920X1080.h264.AVC.AsiaRa.mkv``` which is a unit test case and must return `screenSize` = `1080p`.

I need to invalidate `screenSize` if width or height is less than `100`, for `season` and `episodeNumber` to have priority in this case.

**Comment by Toilal** [comment]
FYI @dingho, it still guess `episodeList`, but `episodeNumber` is now `9` as expected.

**Comment by dingho** [comment]
Thank you.  I'll give it a try.

**Comment by dingho** [comment]
Thank you.  Working as expected.
