### ISSUE TITLE
Wrong detection of episode name

### ISSUE THREAD

**Issue by superphil0** [wackou/guessit#234]
When guessing Californication - S05E09 - At the Movies [HDTV-720p].mkv
This results in:
{
  "type": "episode",
  "container": "mkv",
  "season": 5,
  "title": "the Movies",
  "episodeNumber": 9,
  "screenSize": "720p",
  "country": "AT",
  "series": "Californication (AT)",
  "format": "HDTV",
  "mimetype": "video/x-matroska"
}

clearly the AT is detected as country even though it is part of the episode name

**Comment by Toilal** [comment]
I'm currently rewriting guessit from scratch in 2.x branch. This issue is quite hard to solve in current version, and I don't want to invest more time in it for now.

It will be fixed in 2.x as design is totally rethinked, but it's still a good use case to include in future unit tests.

**Comment by pannal** [comment]
I've got a user from Sub-Zero (implements subliminal, implements guessit), who'd like to get his episode matched: `Series_name.2005.211.episode.title.avi`.

Is that also considered for guessit 2 or can this be fixed in guessit 1, already?

**Comment by Toilal** [comment]
Please open another issue. This is an interesting case too.

**Comment by Toilal** [comment]
This one is currently fixed in `2.x`. I'll close the issue on first alpha release, it should be released this week.

**Comment by Toilal** [comment]
In guessit 2.0a2

```
For: Californication - S05E09 - At the Movies [HDTV-720p].mkv
GuessIt found: {
    "title": "Californication", 
    "season": 5, 
    "episode": 9, 
    "episode_title": "At the Movies", 
    "format": "HDTV", 
    "screen_size": "720p", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```
